const Types = {
  AUTH_INIT: 'AUTH_INIT',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAILURE: 'AUTH_FAILURE',

  VOUCHER_AUTH_INIT: 'VOUCHER_AUTH_INIT',
  VOUCHER_AUTH_SUCCESS: 'VOUCHER_AUTH_SUCCESS',
  VOUCHER_AUTH_FAILURE: 'VOUCHER_AUTH_FAILURE',
};

export default Types;
