const types = {
    POST_NEW_USER: "POST_NEW_USER",
    POST_NEW_USER_SUCCESS: "POST_NEW_USER_SUCCESS",
    POST_NEW_USER_FAILURE: "POST_NEW_USER_FAILURE",

    FETCH_USERS: "FETCH_USERS",
    FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",
    FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
    SET_USERS_LIST: "SET_USERS_LIST",
    SET_ACTIVE_USER: "SET_ACTIVE_USER",

    POST_SYSTEM_SETTINGS: "POST_SYSTEM_SETTINGS",
    FETCH_SYSTEM_SETTINGS: "FETCH_SYSTEM_SETTINGS",
    SET_SYSTEM_SETTINGS: "SET_SYSTEM_SETTINGS",
    
    SET_PERMISSION_GROUPS_LIST: "SET_PERMISSION_GROUPS_LIST",
    SET_ENGR_PERMISSION_GROUPS_LIST: "SET_ENGR_PERMISSION_GROUPS_LIST"
};

export default types;